
name: linter

on:
  push:
    branches: [master]
    paths:
      - '**/*.go'

  pull_request:
    branches: [master]
    paths:
      - '**/*.go'

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'   # explicitly set your target Go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest        # always pulls the latest golangci-lint

